---
apiVersion: v1
kind: ConfigMap
metadata:
  name: 'ambassador-proxy-config'
data:
  proxy.conf:
    server {
      listen 9102;
      listen [::]:9102;

      server_name _;

      location /stats {
        proxy_pass http://127.0.0.1:8001;
        proxy_http_version 1.1;
      }
    }
