---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  labels:
    app: ambassador
    chart: ambassador-0.60.3
    release: test
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: ambassador
    release: test
