---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ambassador
  labels:
    app: ambassador
    chart: ambassador-0.60.3
    release: test
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ambassador
      release: test
  template:
    metadata:
      labels:
        service: ambassador
        app: ambassador
        release: test
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
    spec:
      serviceAccountName: ambassador
      volumes:
      - name: proxy-conf
        configMap:
          name: ambassador-proxy-config
      containers:
        # TODO: make metrics-proxy configurable
        - name: metrics-proxy
          image: nginx:1.15
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 50m
              memory: 16Mi
          ports:
          - name: metrics
            containerPort: 9102
          volumeMounts:
          - mountPath: /etc/nginx/conf.d
            name: proxy-conf
            readOnly: true
        - name: ambassador
          image: quay.io/datawire/ambassador:0.60.3
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
            - name: admin
              containerPort: 8877
          env:
          - name: STATSD_ENABLED
            value: "true"
          - name: STATSD_HOST
            value: localhost
          - name: AMBASSADOR_SINGLE_NAMESPACE
            value: "true"
          - name: AMBASSADOR_VERIFY_SSL_FALSE
            value: "false"
          - name: AMBASSADOR_ID
            value: "default"
          - name: AMBASSADOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          livenessProbe:
            httpGet:
              path: /ambassador/v0/check_alive
              port: admin
            initialDelaySeconds: 30
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ambassador/v0/check_ready
              port: admin
            initialDelaySeconds: 30
            periodSeconds: 3
